// CodeGear C++Builder
// Copyright (c) 1995, 2015 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'OnGuardFMXDR.dpk' rev: 29.00 (iOSSIM)

#ifndef OnguardfmxdrHPP
#define OnguardfmxdrHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FMX.ogfile.hpp>
#include <FMX.ogfirst.hpp>
#include <FMX.ognetwrk.hpp>
#include <FMX.ogposix.hpp>
#include <FMX.ogutil.hpp>
#include <FMX.onguard.hpp>
#include <FMX.onguard1.hpp>
#include <FMX.onguard2.hpp>
#include <FMX.onguard3.hpp>
#include <FMX.onguard4.hpp>
#include <Posix.Base.hpp>	// (rtl)
#include <Posix.StdDef.hpp>	// (rtl)
#include <Posix.SysTypes.hpp>	// (rtl)
#include <Posix.SysStat.hpp>	// (rtl)
#include <Posix.Fcntl.hpp>	// (rtl)
#include <Posix.Stdio.hpp>	// (rtl)
#include <System.Types.hpp>	// (rtl)
#include <Posix.Dlfcn.hpp>	// (rtl)
#include <Posix.Signal.hpp>	// (rtl)
#include <Posix.Time.hpp>	// (rtl)
#include <Posix.SysTime.hpp>	// (rtl)
#include <System.Internal.Unwinder.hpp>	// (rtl)
#include <Macapi.Mach.hpp>	// (rtl)
#include <Macapi.CoreServices.hpp>	// (rtl)
#include <Macapi.CoreFoundation.hpp>	// (rtl)
#include <System.SysConst.hpp>	// (rtl)
#include <Posix.Iconv.hpp>	// (rtl)
#include <Posix.Dirent.hpp>	// (rtl)
#include <Posix.Errno.hpp>	// (rtl)
#include <Posix.Fnmatch.hpp>	// (rtl)
#include <Posix.Locale.hpp>	// (rtl)
#include <Posix.Langinfo.hpp>	// (rtl)
#include <Posix.Sched.hpp>	// (rtl)
#include <Posix.Pthread.hpp>	// (rtl)
#include <Posix.Stdlib.hpp>	// (rtl)
#include <Posix.String_.hpp>	// (rtl)
#include <Posix.SysSysctl.hpp>	// (rtl)
#include <Posix.Unistd.hpp>	// (rtl)
#include <Posix.Utime.hpp>	// (rtl)
#include <Posix.Wordexp.hpp>	// (rtl)
#include <Posix.Pwd.hpp>	// (rtl)
#include <Posix.SysUio.hpp>	// (rtl)
#include <Posix.SysSocket.hpp>	// (rtl)
#include <Posix.ArpaInet.hpp>	// (rtl)
#include <Posix.NetinetIn.hpp>	// (rtl)
#include <Macapi.ObjCRuntime.hpp>	// (rtl)
#include <System.RTLConsts.hpp>	// (rtl)
#include <Posix.Wchar.hpp>	// (rtl)
#include <Posix.Wctype.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.MachExceptions.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <Posix.NetIf.hpp>	// (rtl)
#include <iOSapi.CocoaTypes.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <Posix.SysMman.hpp>	// (rtl)
#include <System.Internal.Unwind.hpp>	// (rtl)
#include <System.Hash.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Generics.Collections.hpp>	// (rtl)
#include <Macapi.OCMarshal.hpp>	// (rtl)
#include <Macapi.Consts.hpp>	// (rtl)
#include <Macapi.OCBlocks.hpp>	// (rtl)
#include <Macapi.ObjectiveC.hpp>	// (rtl)
#include <iOSapi.Foundation.hpp>	// (rtl)
#include <iOSapi.CoreGraphics.hpp>	// (rtl)
#include <iOSapi.QuartzCore.hpp>	// (rtl)
#include <iOSapi.CoreData.hpp>	// (rtl)
#include <iOSapi.OpenGLES.hpp>	// (rtl)
#include <iOSapi.CoreImage.hpp>	// (rtl)
#include <iOSapi.CoreText.hpp>	// (rtl)
#include <iOSapi.UIKit.hpp>	// (rtl)
#include <Posix.StrOpts.hpp>	// (rtl)
#include <Posix.SysSelect.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.UITypes.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <System.StrUtils.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.ImageList.hpp>	// (rtl)
#include <System.Math.Vectors.hpp>	// (rtl)
#include <FMX.Consts.hpp>	// (fmx)
#include <System.iOS.Devices.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <System.Analytics.hpp>	// (rtl)
#include <FMX.Surfaces.hpp>	// (fmx)
#include <System.RegularExpressionsAPI.hpp>	// (rtl)
#include <System.RegularExpressionsConsts.hpp>	// (rtl)
#include <System.RegularExpressionsCore.hpp>	// (rtl)
#include <System.RegularExpressions.hpp>	// (rtl)
#include <FMX.Text.hpp>	// (fmx)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <FMX.Materials.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <Macapi.Helpers.hpp>	// (rtl)
#include <iOSapi.GLKit.hpp>	// (rtl)
#include <FMX.MultiTouch.hpp>	// (fmx)
#include <FMX.Gestures.iOS.hpp>	// (fmx)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.MultiTouch.iOS.hpp>	// (fmx)
#include <FMX.Helpers.iOS.hpp>	// (fmx)
#include <FMX.ZOrder.iOS.hpp>	// (fmx)
#include <Posix.Semaphore.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Diagnostics.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <System.Masks.hpp>	// (rtl)
#include <System.Mac.CFUtils.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <FMX.Objects.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <FMX.StdActns.hpp>	// (fmx)
#include <FMX.Presentation.Messages.hpp>	// (fmx)
#include <FMX.Controls.Model.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.Presentation.Style.hpp>	// (fmx)
#include <FMX.Presentation.iOS.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Materials.Canvas.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.FontGlyphs.iOS.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.StrokeBuilder.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.Context.GLES.hpp>	// (fmx)
#include <FMX.Context.GLES.iOS.hpp>	// (fmx)
#include <FMX.Presentation.iOS.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.ImgList.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.Switch.iOS.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <FMX.Pickers.iOS.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.WebBrowser.Delegate.iOS.hpp>	// (fmx)
#include <FMX.WebBrowser.Cocoa.hpp>	// (fmx)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.Controls3D.hpp>	// (fmx)
#include <FMX.MaterialSources.hpp>	// (fmx)
#include <FMX.Import.hpp>	// (fmx)
#include <FMX.Objects3D.hpp>	// (fmx)
#include <FMX.Forms3D.hpp>	// (fmx)
#include <FMX.Graphics.iOS.hpp>	// (fmx)
#include <FMX.Controls.iOS.hpp>	// (fmx)
#include <FMX.ListView.Types.hpp>	// (fmx)
#include <FMX.ListView.iOS.hpp>	// (fmx)
#include <Macapi.Dispatch.hpp>	// (rtl)
#include <iOSapi.CoreLocation.hpp>	// (rtl)
#include <iOSapi.MapKit.hpp>	// (rtl)
#include <FMX.Maps.iOS.hpp>	// (fmx)
#include <FMX.Maps.hpp>	// (fmx)
#include <FMX.Platform.iOS.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.iOS.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <FMX.Platform.Common.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.ActnList.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.SpellChecker.iOS.hpp>	// (fmx)
#include <FMX.SpellChecker.hpp>	// (fmx)
#include <FMX.Edit.Style.hpp>	// (fmx)
#include <FMX.Edit.iOS.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.ListBox.Selection.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.ComboEdit.Style.hpp>	// (fmx)
#include <FMX.ComboEdit.hpp>	// (fmx)
#include <FMX.ComboTrackBar.Style.hpp>	// (fmx)
#include <FMX.ComboTrackBar.hpp>	// (fmx)
#include <FMX.EditBox.Style.hpp>	// (fmx)
#include <FMX.EditBox.hpp>	// (fmx)
#include <FMX.SpinBox.Style.hpp>	// (fmx)
#include <FMX.SpinBox.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <FMX.TabControl.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.CalendarEdit.Style.hpp>	// (fmx)
#include <FMX.CalendarEdit.hpp>	// (fmx)
#include <FMX.NumberBox.Style.hpp>	// (fmx)
#include <FMX.NumberBox.hpp>	// (fmx)
#include <FMX.Memo.Types.hpp>	// (fmx)
#include <FMX.ScrollBox.Style.hpp>	// (fmx)
#include <FMX.ScrollBox.iOS.hpp>	// (fmx)
#include <FMX.ScrollBox.hpp>	// (fmx)
#include <FMX.Memo.Style.hpp>	// (fmx)
#include <FMX.Memo.iOS.hpp>	// (fmx)
#include <FMX.Memo.hpp>	// (fmx)
#include <System.IniFiles.hpp>	// (rtl)

//-- user supplied -----------------------------------------------------------

namespace Onguardfmxdr
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Onguardfmxdr */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_ONGUARDFMXDR)
using namespace Onguardfmxdr;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// OnguardfmxdrHPP
